### ISSUE TITLE
Buscar y ver tutoriales sobre MongoDB

### ISSUE THREAD

**Issue by StephaniePC** [StephaniePC/Proyecto--PartidosFut5#3]
Buscar como funciona y como se instala, además de como se conecta a c#

**Comment by mejiadavid** [comment]
Este video me parece muy util, el unico problema es que trabajan sobre una BD ya creada. pero como hacer la conexion y el query esta muy util.
https://www.youtube.com/watch?v=rMbIx4Yk6U8

**Comment by j0hnnatan** [comment]
En este video vienen los pasos a seguir de como instalar MongoDB.
https://youtu.be/1uFY60CESlM
https://www.youtube.com/watch?v=pWbMrx5rVBE
https://www.youtube.com/watch?v=xVnQwvsK-eY
